patch:
  __include: rime_ice_suggestion:/
  "menu/page_size": 4
  schema_list:
    - schema: rime_ice
  "ascii_composer/good_old_caps_lock": true
  "ascii_composer/switch_key":
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
  "switcher/hotkeys":
    - "Control+Shift+F4"
